# coding: utf-8

"""
    HOPRd Rest API v2

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.settings_setting_body import SettingsSettingBody  # noqa: E501
from swagger_client.rest import ApiException


class TestSettingsSettingBody(unittest.TestCase):
    """SettingsSettingBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettingsSettingBody(self):
        """Test SettingsSettingBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.settings_setting_body.SettingsSettingBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
