# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.2.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.node_api import NodeApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestNodeApi(unittest.TestCase):
    """NodeApi unit test stubs"""

    def setUp(self):
        self.api = NodeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entry_nodes(self):
        """Test case for entry_nodes

        List all known entry nodes with multiaddrs and eligibility.  # noqa: E501
        """
        pass

    def test_info(self):
        """Test case for info

        Get information about this HOPR Node.  # noqa: E501
        """
        pass

    def test_metrics(self):
        """Test case for metrics

        Retrieve Prometheus metrics from the running node.  # noqa: E501
        """
        pass

    def test_peers(self):
        """Test case for peers

        Lists information for `connected peers` and `announced peers`.  # noqa: E501
        """
        pass

    def test_version(self):
        """Test case for version

        Get release version of the running node.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
