# coding: utf-8

"""
    hoprd-api

    API server using the hopr-lib created HOPR node and exposing it using a HTTP REST API  # noqa: E501

    OpenAPI spec version: 0.2.1
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.tickets_api import TicketsApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestTicketsApi(unittest.TestCase):
    """TicketsApi unit test stubs"""

    def setUp(self):
        self.api = TicketsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_redeem_all_tickets(self):
        """Test case for redeem_all_tickets

        Starts redeeming of all tickets in all channels.  # noqa: E501
        """
        pass

    def test_show_all_tickets(self):
        """Test case for show_all_tickets

        Returns all the tickets in all the channels.  # noqa: E501
        """
        pass

    def test_show_ticket_statistics(self):
        """Test case for show_ticket_statistics

        Returns current complete statistics on tickets.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
