# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.1.1
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.configuration_api import ConfigurationApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = ConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_configuration(self):
        """Test case for configuration

        Get the configuration of the running node.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
