# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2001_heartbeats import InlineResponse2001Heartbeats  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2001Heartbeats(unittest.TestCase):
    """InlineResponse2001Heartbeats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Heartbeats(self):
        """Test InlineResponse2001Heartbeats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2001_heartbeats.InlineResponse2001Heartbeats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
