# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.models.inline_response2011 import InlineResponse2011  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestInlineResponse2011(unittest.TestCase):
    """InlineResponse2011 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2011(self):
        """Test InlineResponse2011"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hoprd_sdk.models.inline_response2011.InlineResponse2011()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
