# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.models.ping_response import PingResponse  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestPingResponse(unittest.TestCase):
    """PingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPingResponse(self):
        """Test PingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hoprd_sdk.models.ping_response.PingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
