# coding: utf-8

"""
    hoprd-api

    API server using the hopr-lib created HOPR node and exposing it using a HTTP REST API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.channels_api import ChannelsApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self):
        self.api = ChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aggregate_tickets_in_channel(self):
        """Test case for aggregate_tickets_in_channel

        """
        pass

    def test_close_channel(self):
        """Test case for close_channel

        """
        pass

    def test_fund_channel(self):
        """Test case for fund_channel

        """
        pass

    def test_list_channels(self):
        """Test case for list_channels

        """
        pass

    def test_open_channel(self):
        """Test case for open_channel

        """
        pass

    def test_redeem_tickets_in_channel(self):
        """Test case for redeem_tickets_in_channel

        """
        pass

    def test_show_channel(self):
        """Test case for show_channel

        """
        pass

    def test_show_channel_tickets(self):
        """Test case for show_channel_tickets

        """
        pass


if __name__ == '__main__':
    unittest.main()
