# coding: utf-8

"""
    HOPRd Rest API v2

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.token_capability import TokenCapability  # noqa: E501
from swagger_client.rest import ApiException


class TestTokenCapability(unittest.TestCase):
    """TokenCapability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenCapability(self):
        """Test TokenCapability"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.token_capability.TokenCapability()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
