# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.1.1
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.alias_api import AliasApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestAliasApi(unittest.TestCase):
    """AliasApi unit test stubs"""

    def setUp(self):
        self.api = AliasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aliases(self):
        """Test case for aliases

        (deprecated, will be removed in v3.0) Get each previously set alias and its corresponding PeerId.  # noqa: E501
        """
        pass

    def test_clear_aliases(self):
        """Test case for clear_aliases

        (deprecated, will be removed in v3.0) Clear all aliases.  # noqa: E501
        """
        pass

    def test_delete_alias(self):
        """Test case for delete_alias

        (deprecated, will be removed in v3.0) Delete an alias.  # noqa: E501
        """
        pass

    def test_get_alias(self):
        """Test case for get_alias

        (deprecated, will be removed in v3.0) Get alias for the PeerId (Hopr address) that have this alias assigned to it.  # noqa: E501
        """
        pass

    def test_set_alias(self):
        """Test case for set_alias

        (deprecated, will be removed in v3.0) Set alias for a peer with a specific PeerId.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
