# coding: utf-8

"""
    hoprd-api

    API server using the hopr-lib created HOPR node and exposing it using a HTTP REST API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.channel_api import ChannelApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestChannelApi(unittest.TestCase):
    """ChannelApi unit test stubs"""

    def setUp(self):
        self.api = ChannelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aggregate_tickets_in_channel(self):
        """Test case for aggregate_tickets_in_channel

        """
        pass

    def test_redeem_tickets_in_channel(self):
        """Test case for redeem_tickets_in_channel

        """
        pass


if __name__ == '__main__':
    unittest.main()
