# coding: utf-8

"""
    hoprd-api

    API server using the hopr-lib created HOPR node and exposing it using a HTTP REST API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.alias_api import AliasApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestAliasApi(unittest.TestCase):
    """AliasApi unit test stubs"""

    def setUp(self):
        self.api = AliasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aliases(self):
        """Test case for aliases

        Get each previously set alias and its corresponding PeerId  # noqa: E501
        """
        pass

    def test_delete_alias(self):
        """Test case for delete_alias

        Delete an alias.  # noqa: E501
        """
        pass

    def test_get_alias(self):
        """Test case for get_alias

        Get alias for the PeerId (Hopr address) that have this alias assigned to it.  # noqa: E501
        """
        pass

    def test_set_alias(self):
        """Test case for set_alias

        Set alias for a peer with a specific PeerId.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
