# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.check_healthiness_api import CheckHealthinessApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestCheckHealthinessApi(unittest.TestCase):
    """CheckHealthinessApi unit test stubs"""

    def setUp(self):
        self.api = CheckHealthinessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_node_healthy(self):
        """Test case for check_node_healthy

        """
        pass


if __name__ == '__main__':
    unittest.main()
