# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.channels_api import ChannelsApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self):
        self.api = ChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_channels_aggregate_tickets(self):
        """Test case for channels_aggregate_tickets

        """
        pass

    def test_channels_close_channel(self):
        """Test case for channels_close_channel

        """
        pass

    def test_channels_fund_channel(self):
        """Test case for channels_fund_channel

        """
        pass

    def test_channels_get_channel(self):
        """Test case for channels_get_channel

        """
        pass

    def test_channels_get_channels(self):
        """Test case for channels_get_channels

        """
        pass

    def test_channels_get_tickets(self):
        """Test case for channels_get_tickets

        """
        pass

    def test_channels_open_channel(self):
        """Test case for channels_open_channel

        """
        pass

    def test_channels_redeem_tickets(self):
        """Test case for channels_redeem_tickets

        """
        pass


if __name__ == '__main__':
    unittest.main()
