# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response4221 import InlineResponse4221  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse4221(unittest.TestCase):
    """InlineResponse4221 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4221(self):
        """Test InlineResponse4221"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response4221.InlineResponse4221()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
