# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.10.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.models.alias_destination_body_request import AliasDestinationBodyRequest  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestAliasDestinationBodyRequest(unittest.TestCase):
    """AliasDestinationBodyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAliasDestinationBodyRequest(self):
        """Test AliasDestinationBodyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hoprd_sdk.models.alias_destination_body_request.AliasDestinationBodyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
