# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.aliases_api import AliasesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAliasesApi(unittest.TestCase):
    """AliasesApi unit test stubs"""

    def setUp(self):
        self.api = AliasesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aliases_get_alias(self):
        """Test case for aliases_get_alias

        """
        pass

    def test_aliases_get_aliases(self):
        """Test case for aliases_get_aliases

        """
        pass

    def test_aliases_remove_alias(self):
        """Test case for aliases_remove_alias

        """
        pass

    def test_aliases_set_alias(self):
        """Test case for aliases_set_alias

        """
        pass


if __name__ == '__main__':
    unittest.main()
