# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.10.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.session_api import SessionApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestSessionApi(unittest.TestCase):
    """SessionApi unit test stubs"""

    def setUp(self):
        self.api = SessionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_close_client(self):
        """Test case for close_client

        Closes an existing Session listener.  # noqa: E501
        """
        pass

    def test_create_client(self):
        """Test case for create_client

        Creates a new client session returning the given session listening host and port over TCP or UDP.  # noqa: E501
        """
        pass

    def test_list_clients(self):
        """Test case for list_clients

        Lists existing Session listeners for the given IP protocol.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
