# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.2.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.models.tag_query_request import TagQueryRequest  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestTagQueryRequest(unittest.TestCase):
    """TagQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagQueryRequest(self):
        """Test TagQueryRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hoprd_sdk.models.tag_query_request.TagQueryRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
