# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.messages_api import MessagesApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_messages_delete_messages(self):
        """Test case for messages_delete_messages

        """
        pass

    def test_messages_get_size(self):
        """Test case for messages_get_size

        """
        pass

    def test_messages_peek_all_message(self):
        """Test case for messages_peek_all_message

        """
        pass

    def test_messages_peek_message(self):
        """Test case for messages_peek_message

        """
        pass

    def test_messages_pop_all_message(self):
        """Test case for messages_pop_all_message

        """
        pass

    def test_messages_pop_message(self):
        """Test case for messages_pop_message

        """
        pass

    def test_messages_send_message(self):
        """Test case for messages_send_message

        """
        pass

    def test_messages_websocket(self):
        """Test case for messages_websocket

        """
        pass


if __name__ == '__main__':
    unittest.main()
