# coding: utf-8

"""
    hoprd-api

    API server using the hopr-lib created HOPR node and exposing it using a HTTP REST API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.api.peers_api import PeersApi  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestPeersApi(unittest.TestCase):
    """PeersApi unit test stubs"""

    def setUp(self):
        self.api = PeersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ping_peer(self):
        """Test case for ping_peer

        """
        pass

    def test_show_peer_info(self):
        """Test case for show_peer_info

        """
        pass


if __name__ == '__main__':
    unittest.main()
