# coding: utf-8

"""
    hoprd-api

    API server using the hopr-lib created HOPR node and exposing it using a HTTP REST API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.models.node_peers_res import NodePeersRes  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestNodePeersRes(unittest.TestCase):
    """NodePeersRes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodePeersRes(self):
        """Test NodePeersRes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hoprd_sdk.models.node_peers_res.NodePeersRes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
