# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tokens_api import TokensApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTokensApi(unittest.TestCase):
    """TokensApi unit test stubs"""

    def setUp(self):
        self.api = TokensApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tokens_create(self):
        """Test case for tokens_create

        """
        pass

    def test_tokens_delete(self):
        """Test case for tokens_delete

        """
        pass

    def test_tokens_get_token(self):
        """Test case for tokens_get_token

        """
        pass


if __name__ == '__main__':
    unittest.main()
