# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hoprd_sdk
from hoprd_sdk.models.inline_response20014 import InlineResponse20014  # noqa: E501
from hoprd_sdk.rest import ApiException


class TestInlineResponse20014(unittest.TestCase):
    """InlineResponse20014 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20014(self):
        """Test InlineResponse20014"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hoprd_sdk.models.inline_response20014.InlineResponse20014()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
