# coding: utf-8

"""
    HOPRd Rest API v2

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2001(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'latency': 'float',
        'reported_version': 'str'
    }

    attribute_map = {
        'latency': 'latency',
        'reported_version': 'reportedVersion'
    }

    def __init__(self, latency=None, reported_version=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger"""  # noqa: E501
        self._latency = None
        self._reported_version = None
        self.discriminator = None
        if latency is not None:
            self.latency = latency
        if reported_version is not None:
            self.reported_version = reported_version

    @property
    def latency(self):
        """Gets the latency of this InlineResponse2001.  # noqa: E501

        Number of milliseconds it took to get the response from the pinged node.  # noqa: E501

        :return: The latency of this InlineResponse2001.  # noqa: E501
        :rtype: float
        """
        return self._latency

    @latency.setter
    def latency(self, latency):
        """Sets the latency of this InlineResponse2001.

        Number of milliseconds it took to get the response from the pinged node.  # noqa: E501

        :param latency: The latency of this InlineResponse2001.  # noqa: E501
        :type: float
        """

        self._latency = latency

    @property
    def reported_version(self):
        """Gets the reported_version of this InlineResponse2001.  # noqa: E501

        HOPR protocol version as determined from the successful ping in the Major.Minor.Patch format or \"unknown\"  # noqa: E501

        :return: The reported_version of this InlineResponse2001.  # noqa: E501
        :rtype: str
        """
        return self._reported_version

    @reported_version.setter
    def reported_version(self, reported_version):
        """Sets the reported_version of this InlineResponse2001.

        HOPR protocol version as determined from the successful ping in the Major.Minor.Patch format or \"unknown\"  # noqa: E501

        :param reported_version: The reported_version of this InlineResponse2001.  # noqa: E501
        :type: str
        """

        self._reported_version = reported_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
