# coding: utf-8

"""
    HOPRd Rest API v2

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Ticket(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'counterparty': 'HoprAddress',
        'challenge': 'str',
        'epoch': 'str',
        'index': 'str',
        'amount': 'str',
        'win_prob': 'str',
        'channel_epoch': 'str',
        'signature': 'Signature'
    }

    attribute_map = {
        'counterparty': 'counterparty',
        'challenge': 'challenge',
        'epoch': 'epoch',
        'index': 'index',
        'amount': 'amount',
        'win_prob': 'winProb',
        'channel_epoch': 'channelEpoch',
        'signature': 'signature'
    }

    def __init__(self, counterparty=None, challenge=None, epoch=None, index=None, amount=None, win_prob=None, channel_epoch=None, signature=None):  # noqa: E501
        """Ticket - a model defined in Swagger"""  # noqa: E501
        self._counterparty = None
        self._challenge = None
        self._epoch = None
        self._index = None
        self._amount = None
        self._win_prob = None
        self._channel_epoch = None
        self._signature = None
        self.discriminator = None
        if counterparty is not None:
            self.counterparty = counterparty
        if challenge is not None:
            self.challenge = challenge
        if epoch is not None:
            self.epoch = epoch
        if index is not None:
            self.index = index
        if amount is not None:
            self.amount = amount
        if win_prob is not None:
            self.win_prob = win_prob
        if channel_epoch is not None:
            self.channel_epoch = channel_epoch
        if signature is not None:
            self.signature = signature

    @property
    def counterparty(self):
        """Gets the counterparty of this Ticket.  # noqa: E501


        :return: The counterparty of this Ticket.  # noqa: E501
        :rtype: HoprAddress
        """
        return self._counterparty

    @counterparty.setter
    def counterparty(self, counterparty):
        """Sets the counterparty of this Ticket.


        :param counterparty: The counterparty of this Ticket.  # noqa: E501
        :type: HoprAddress
        """

        self._counterparty = counterparty

    @property
    def challenge(self):
        """Gets the challenge of this Ticket.  # noqa: E501

        The ticket's challenge which needs to be solved before being able to claim the embedded incentive.  # noqa: E501

        :return: The challenge of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._challenge

    @challenge.setter
    def challenge(self, challenge):
        """Sets the challenge of this Ticket.

        The ticket's challenge which needs to be solved before being able to claim the embedded incentive.  # noqa: E501

        :param challenge: The challenge of this Ticket.  # noqa: E501
        :type: str
        """

        self._challenge = challenge

    @property
    def epoch(self):
        """Gets the epoch of this Ticket.  # noqa: E501

        Ticket redemption relies on providing the value opening to a series of commitments that have previously been stored on-chain by the ticket recipient.  # noqa: E501

        :return: The epoch of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._epoch

    @epoch.setter
    def epoch(self, epoch):
        """Sets the epoch of this Ticket.

        Ticket redemption relies on providing the value opening to a series of commitments that have previously been stored on-chain by the ticket recipient.  # noqa: E501

        :param epoch: The epoch of this Ticket.  # noqa: E501
        :type: str
        """

        self._epoch = epoch

    @property
    def index(self):
        """Gets the index of this Ticket.  # noqa: E501

        Each ticket is labeled by an ongoing serial number named ticket index i and its current value is stored in the smart contract.  # noqa: E501

        :return: The index of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this Ticket.

        Each ticket is labeled by an ongoing serial number named ticket index i and its current value is stored in the smart contract.  # noqa: E501

        :param index: The index of this Ticket.  # noqa: E501
        :type: str
        """

        self._index = index

    @property
    def amount(self):
        """Gets the amount of this Ticket.  # noqa: E501

        The ticket's value in HOPR.  # noqa: E501

        :return: The amount of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Ticket.

        The ticket's value in HOPR.  # noqa: E501

        :param amount: The amount of this Ticket.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def win_prob(self):
        """Gets the win_prob of this Ticket.  # noqa: E501

        The ticket's winning probability normalized with the common base of Ethereum which is 2^256-1.  # noqa: E501

        :return: The win_prob of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._win_prob

    @win_prob.setter
    def win_prob(self, win_prob):
        """Sets the win_prob of this Ticket.

        The ticket's winning probability normalized with the common base of Ethereum which is 2^256-1.  # noqa: E501

        :param win_prob: The win_prob of this Ticket.  # noqa: E501
        :type: str
        """

        self._win_prob = win_prob

    @property
    def channel_epoch(self):
        """Gets the channel_epoch of this Ticket.  # noqa: E501

        Payment channels might run through multiple open and close sequences, this epoch tracks the sequence.  # noqa: E501

        :return: The channel_epoch of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._channel_epoch

    @channel_epoch.setter
    def channel_epoch(self, channel_epoch):
        """Sets the channel_epoch of this Ticket.

        Payment channels might run through multiple open and close sequences, this epoch tracks the sequence.  # noqa: E501

        :param channel_epoch: The channel_epoch of this Ticket.  # noqa: E501
        :type: str
        """

        self._channel_epoch = channel_epoch

    @property
    def signature(self):
        """Gets the signature of this Ticket.  # noqa: E501


        :return: The signature of this Ticket.  # noqa: E501
        :rtype: Signature
        """
        return self._signature

    @signature.setter
    def signature(self, signature):
        """Sets the signature of this Ticket.


        :param signature: The signature of this Ticket.  # noqa: E501
        :type: Signature
        """

        self._signature = signature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Ticket, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Ticket):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
