# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.10.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CloseChannelResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel_status': 'str',
        'receipt': 'str'
    }

    attribute_map = {
        'channel_status': 'channelStatus',
        'receipt': 'receipt'
    }

    def __init__(self, channel_status=None, receipt=None):  # noqa: E501
        """CloseChannelResponse - a model defined in Swagger"""  # noqa: E501
        self._channel_status = None
        self._receipt = None
        self.discriminator = None
        self.channel_status = channel_status
        self.receipt = receipt

    @property
    def channel_status(self):
        """Gets the channel_status of this CloseChannelResponse.  # noqa: E501

        New status of the channel. Will be one of `Closed` or `PendingToClose`.  # noqa: E501

        :return: The channel_status of this CloseChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._channel_status

    @channel_status.setter
    def channel_status(self, channel_status):
        """Sets the channel_status of this CloseChannelResponse.

        New status of the channel. Will be one of `Closed` or `PendingToClose`.  # noqa: E501

        :param channel_status: The channel_status of this CloseChannelResponse.  # noqa: E501
        :type: str
        """
        if channel_status is None:
            raise ValueError("Invalid value for `channel_status`, must not be `None`")  # noqa: E501

        self._channel_status = channel_status

    @property
    def receipt(self):
        """Gets the receipt of this CloseChannelResponse.  # noqa: E501

        Receipt for the channel close transaction.  # noqa: E501

        :return: The receipt of this CloseChannelResponse.  # noqa: E501
        :rtype: str
        """
        return self._receipt

    @receipt.setter
    def receipt(self, receipt):
        """Sets the receipt of this CloseChannelResponse.

        Receipt for the channel close transaction.  # noqa: E501

        :param receipt: The receipt of this CloseChannelResponse.  # noqa: E501
        :type: str
        """
        if receipt is None:
            raise ValueError("Invalid value for `receipt`, must not be `None`")  # noqa: E501

        self._receipt = receipt

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CloseChannelResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloseChannelResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
