# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetMessageBodyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag': 'int',
        'timestamp': 'int'
    }

    attribute_map = {
        'tag': 'tag',
        'timestamp': 'timestamp'
    }

    def __init__(self, tag=None, timestamp=None):  # noqa: E501
        """GetMessageBodyRequest - a model defined in Swagger"""  # noqa: E501
        self._tag = None
        self._timestamp = None
        self.discriminator = None
        if tag is not None:
            self.tag = tag
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def tag(self):
        """Gets the tag of this GetMessageBodyRequest.  # noqa: E501

        The message tag used to filter messages based on application  # noqa: E501

        :return: The tag of this GetMessageBodyRequest.  # noqa: E501
        :rtype: int
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this GetMessageBodyRequest.

        The message tag used to filter messages based on application  # noqa: E501

        :param tag: The tag of this GetMessageBodyRequest.  # noqa: E501
        :type: int
        """

        self._tag = tag

    @property
    def timestamp(self):
        """Gets the timestamp of this GetMessageBodyRequest.  # noqa: E501

        Timestamp to filter messages received after this timestamp  # noqa: E501

        :return: The timestamp of this GetMessageBodyRequest.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this GetMessageBodyRequest.

        Timestamp to filter messages received after this timestamp  # noqa: E501

        :param timestamp: The timestamp of this GetMessageBodyRequest.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetMessageBodyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetMessageBodyRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
