# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2001Heartbeats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sent': 'float',
        'success': 'float'
    }

    attribute_map = {
        'sent': 'sent',
        'success': 'success'
    }

    def __init__(self, sent=None, success=None):  # noqa: E501
        """InlineResponse2001Heartbeats - a model defined in Swagger"""  # noqa: E501
        self._sent = None
        self._success = None
        self.discriminator = None
        if sent is not None:
            self.sent = sent
        if success is not None:
            self.success = success

    @property
    def sent(self):
        """Gets the sent of this InlineResponse2001Heartbeats.  # noqa: E501

        Heartbeats sent to the node  # noqa: E501

        :return: The sent of this InlineResponse2001Heartbeats.  # noqa: E501
        :rtype: float
        """
        return self._sent

    @sent.setter
    def sent(self, sent):
        """Sets the sent of this InlineResponse2001Heartbeats.

        Heartbeats sent to the node  # noqa: E501

        :param sent: The sent of this InlineResponse2001Heartbeats.  # noqa: E501
        :type: float
        """

        self._sent = sent

    @property
    def success(self):
        """Gets the success of this InlineResponse2001Heartbeats.  # noqa: E501

        Successful heartbeats sent to the node  # noqa: E501

        :return: The success of this InlineResponse2001Heartbeats.  # noqa: E501
        :rtype: float
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this InlineResponse2001Heartbeats.

        Successful heartbeats sent to the node  # noqa: E501

        :param success: The success of this InlineResponse2001Heartbeats.  # noqa: E501
        :type: float
        """

        self._success = success

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001Heartbeats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001Heartbeats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
