# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MessagesBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag': 'MessageTag',
        'body': 'MessageBody',
        'peer_address': 'str',
        'path': 'list[str]',
        'hops': 'int'
    }

    attribute_map = {
        'tag': 'tag',
        'body': 'body',
        'peer_address': 'peerAddress',
        'path': 'path',
        'hops': 'hops'
    }

    def __init__(self, tag=None, body=None, peer_address=None, path=None, hops=None):  # noqa: E501
        """MessagesBody - a model defined in Swagger"""  # noqa: E501
        self._tag = None
        self._body = None
        self._peer_address = None
        self._path = None
        self._hops = None
        self.discriminator = None
        self.tag = tag
        self.body = body
        self.peer_address = peer_address
        if path is not None:
            self.path = path
        if hops is not None:
            self.hops = hops

    @property
    def tag(self):
        """Gets the tag of this MessagesBody.  # noqa: E501


        :return: The tag of this MessagesBody.  # noqa: E501
        :rtype: MessageTag
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this MessagesBody.


        :param tag: The tag of this MessagesBody.  # noqa: E501
        :type: MessageTag
        """
        if tag is None:
            raise ValueError("Invalid value for `tag`, must not be `None`")  # noqa: E501

        self._tag = tag

    @property
    def body(self):
        """Gets the body of this MessagesBody.  # noqa: E501


        :return: The body of this MessagesBody.  # noqa: E501
        :rtype: MessageBody
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this MessagesBody.


        :param body: The body of this MessagesBody.  # noqa: E501
        :type: MessageBody
        """
        if body is None:
            raise ValueError("Invalid value for `body`, must not be `None`")  # noqa: E501

        self._body = body

    @property
    def peer_address(self):
        """Gets the peer_address of this MessagesBody.  # noqa: E501

        The recipient HOPR peer id, to which the message is sent.  # noqa: E501

        :return: The peer_address of this MessagesBody.  # noqa: E501
        :rtype: str
        """
        return self._peer_address

    @peer_address.setter
    def peer_address(self, peer_address):
        """Sets the peer_address of this MessagesBody.

        The recipient HOPR peer id, to which the message is sent.  # noqa: E501

        :param peer_address: The peer_address of this MessagesBody.  # noqa: E501
        :type: str
        """
        if peer_address is None:
            raise ValueError("Invalid value for `peer_address`, must not be `None`")  # noqa: E501

        self._peer_address = peer_address

    @property
    def path(self):
        """Gets the path of this MessagesBody.  # noqa: E501

        The path is ordered list of peer ids through which the message should be sent. If no path is provided, a path which covers the nodes minimum required hops will be determined automatically.  # noqa: E501

        :return: The path of this MessagesBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this MessagesBody.

        The path is ordered list of peer ids through which the message should be sent. If no path is provided, a path which covers the nodes minimum required hops will be determined automatically.  # noqa: E501

        :param path: The path of this MessagesBody.  # noqa: E501
        :type: list[str]
        """

        self._path = path

    @property
    def hops(self):
        """Gets the hops of this MessagesBody.  # noqa: E501

        Number of required intermediate nodes. This parameter is ignored if path is set.  # noqa: E501

        :return: The hops of this MessagesBody.  # noqa: E501
        :rtype: int
        """
        return self._hops

    @hops.setter
    def hops(self, hops):
        """Sets the hops of this MessagesBody.

        Number of required intermediate nodes. This parameter is ignored if path is set.  # noqa: E501

        :param hops: The hops of this MessagesBody.  # noqa: E501
        :type: int
        """

        self._hops = hops

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessagesBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessagesBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
