# coding: utf-8

"""
    hoprd-api

    API server using the hopr-lib created HOPR node and exposing it using a HTTP REST API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NodeTicketStatistics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'losing_tickets': 'int',
        'neglected': 'int',
        'neglected_value': 'str',
        'redeemed': 'int',
        'redeemed_value': 'str',
        'rejected': 'int',
        'rejected_value': 'str',
        'unredeemed': 'int',
        'unredeemed_value': 'str',
        'win_proportion': 'float'
    }

    attribute_map = {
        'losing_tickets': 'losingTickets',
        'neglected': 'neglected',
        'neglected_value': 'neglectedValue',
        'redeemed': 'redeemed',
        'redeemed_value': 'redeemedValue',
        'rejected': 'rejected',
        'rejected_value': 'rejectedValue',
        'unredeemed': 'unredeemed',
        'unredeemed_value': 'unredeemedValue',
        'win_proportion': 'winProportion'
    }

    def __init__(self, losing_tickets=None, neglected=None, neglected_value=None, redeemed=None, redeemed_value=None, rejected=None, rejected_value=None, unredeemed=None, unredeemed_value=None, win_proportion=None):  # noqa: E501
        """NodeTicketStatistics - a model defined in Swagger"""  # noqa: E501
        self._losing_tickets = None
        self._neglected = None
        self._neglected_value = None
        self._redeemed = None
        self._redeemed_value = None
        self._rejected = None
        self._rejected_value = None
        self._unredeemed = None
        self._unredeemed_value = None
        self._win_proportion = None
        self.discriminator = None
        self.losing_tickets = losing_tickets
        self.neglected = neglected
        self.neglected_value = neglected_value
        self.redeemed = redeemed
        self.redeemed_value = redeemed_value
        self.rejected = rejected
        self.rejected_value = rejected_value
        self.unredeemed = unredeemed
        self.unredeemed_value = unredeemed_value
        self.win_proportion = win_proportion

    @property
    def losing_tickets(self):
        """Gets the losing_tickets of this NodeTicketStatistics.  # noqa: E501


        :return: The losing_tickets of this NodeTicketStatistics.  # noqa: E501
        :rtype: int
        """
        return self._losing_tickets

    @losing_tickets.setter
    def losing_tickets(self, losing_tickets):
        """Sets the losing_tickets of this NodeTicketStatistics.


        :param losing_tickets: The losing_tickets of this NodeTicketStatistics.  # noqa: E501
        :type: int
        """
        if losing_tickets is None:
            raise ValueError("Invalid value for `losing_tickets`, must not be `None`")  # noqa: E501

        self._losing_tickets = losing_tickets

    @property
    def neglected(self):
        """Gets the neglected of this NodeTicketStatistics.  # noqa: E501


        :return: The neglected of this NodeTicketStatistics.  # noqa: E501
        :rtype: int
        """
        return self._neglected

    @neglected.setter
    def neglected(self, neglected):
        """Sets the neglected of this NodeTicketStatistics.


        :param neglected: The neglected of this NodeTicketStatistics.  # noqa: E501
        :type: int
        """
        if neglected is None:
            raise ValueError("Invalid value for `neglected`, must not be `None`")  # noqa: E501

        self._neglected = neglected

    @property
    def neglected_value(self):
        """Gets the neglected_value of this NodeTicketStatistics.  # noqa: E501


        :return: The neglected_value of this NodeTicketStatistics.  # noqa: E501
        :rtype: str
        """
        return self._neglected_value

    @neglected_value.setter
    def neglected_value(self, neglected_value):
        """Sets the neglected_value of this NodeTicketStatistics.


        :param neglected_value: The neglected_value of this NodeTicketStatistics.  # noqa: E501
        :type: str
        """
        if neglected_value is None:
            raise ValueError("Invalid value for `neglected_value`, must not be `None`")  # noqa: E501

        self._neglected_value = neglected_value

    @property
    def redeemed(self):
        """Gets the redeemed of this NodeTicketStatistics.  # noqa: E501


        :return: The redeemed of this NodeTicketStatistics.  # noqa: E501
        :rtype: int
        """
        return self._redeemed

    @redeemed.setter
    def redeemed(self, redeemed):
        """Sets the redeemed of this NodeTicketStatistics.


        :param redeemed: The redeemed of this NodeTicketStatistics.  # noqa: E501
        :type: int
        """
        if redeemed is None:
            raise ValueError("Invalid value for `redeemed`, must not be `None`")  # noqa: E501

        self._redeemed = redeemed

    @property
    def redeemed_value(self):
        """Gets the redeemed_value of this NodeTicketStatistics.  # noqa: E501


        :return: The redeemed_value of this NodeTicketStatistics.  # noqa: E501
        :rtype: str
        """
        return self._redeemed_value

    @redeemed_value.setter
    def redeemed_value(self, redeemed_value):
        """Sets the redeemed_value of this NodeTicketStatistics.


        :param redeemed_value: The redeemed_value of this NodeTicketStatistics.  # noqa: E501
        :type: str
        """
        if redeemed_value is None:
            raise ValueError("Invalid value for `redeemed_value`, must not be `None`")  # noqa: E501

        self._redeemed_value = redeemed_value

    @property
    def rejected(self):
        """Gets the rejected of this NodeTicketStatistics.  # noqa: E501


        :return: The rejected of this NodeTicketStatistics.  # noqa: E501
        :rtype: int
        """
        return self._rejected

    @rejected.setter
    def rejected(self, rejected):
        """Sets the rejected of this NodeTicketStatistics.


        :param rejected: The rejected of this NodeTicketStatistics.  # noqa: E501
        :type: int
        """
        if rejected is None:
            raise ValueError("Invalid value for `rejected`, must not be `None`")  # noqa: E501

        self._rejected = rejected

    @property
    def rejected_value(self):
        """Gets the rejected_value of this NodeTicketStatistics.  # noqa: E501


        :return: The rejected_value of this NodeTicketStatistics.  # noqa: E501
        :rtype: str
        """
        return self._rejected_value

    @rejected_value.setter
    def rejected_value(self, rejected_value):
        """Sets the rejected_value of this NodeTicketStatistics.


        :param rejected_value: The rejected_value of this NodeTicketStatistics.  # noqa: E501
        :type: str
        """
        if rejected_value is None:
            raise ValueError("Invalid value for `rejected_value`, must not be `None`")  # noqa: E501

        self._rejected_value = rejected_value

    @property
    def unredeemed(self):
        """Gets the unredeemed of this NodeTicketStatistics.  # noqa: E501


        :return: The unredeemed of this NodeTicketStatistics.  # noqa: E501
        :rtype: int
        """
        return self._unredeemed

    @unredeemed.setter
    def unredeemed(self, unredeemed):
        """Sets the unredeemed of this NodeTicketStatistics.


        :param unredeemed: The unredeemed of this NodeTicketStatistics.  # noqa: E501
        :type: int
        """
        if unredeemed is None:
            raise ValueError("Invalid value for `unredeemed`, must not be `None`")  # noqa: E501

        self._unredeemed = unredeemed

    @property
    def unredeemed_value(self):
        """Gets the unredeemed_value of this NodeTicketStatistics.  # noqa: E501


        :return: The unredeemed_value of this NodeTicketStatistics.  # noqa: E501
        :rtype: str
        """
        return self._unredeemed_value

    @unredeemed_value.setter
    def unredeemed_value(self, unredeemed_value):
        """Sets the unredeemed_value of this NodeTicketStatistics.


        :param unredeemed_value: The unredeemed_value of this NodeTicketStatistics.  # noqa: E501
        :type: str
        """
        if unredeemed_value is None:
            raise ValueError("Invalid value for `unredeemed_value`, must not be `None`")  # noqa: E501

        self._unredeemed_value = unredeemed_value

    @property
    def win_proportion(self):
        """Gets the win_proportion of this NodeTicketStatistics.  # noqa: E501


        :return: The win_proportion of this NodeTicketStatistics.  # noqa: E501
        :rtype: float
        """
        return self._win_proportion

    @win_proportion.setter
    def win_proportion(self, win_proportion):
        """Sets the win_proportion of this NodeTicketStatistics.


        :param win_proportion: The win_proportion of this NodeTicketStatistics.  # noqa: E501
        :type: float
        """
        if win_proportion is None:
            raise ValueError("Invalid value for `win_proportion`, must not be `None`")  # noqa: E501

        self._win_proportion = win_proportion

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NodeTicketStatistics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeTicketStatistics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
