# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.2.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NodePeersResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'announced': 'list[AnnouncedPeer]',
        'connected': 'list[PeerInfo]'
    }

    attribute_map = {
        'announced': 'announced',
        'connected': 'connected'
    }

    def __init__(self, announced=None, connected=None):  # noqa: E501
        """NodePeersResponse - a model defined in Swagger"""  # noqa: E501
        self._announced = None
        self._connected = None
        self.discriminator = None
        self.announced = announced
        self.connected = connected

    @property
    def announced(self):
        """Gets the announced of this NodePeersResponse.  # noqa: E501


        :return: The announced of this NodePeersResponse.  # noqa: E501
        :rtype: list[AnnouncedPeer]
        """
        return self._announced

    @announced.setter
    def announced(self, announced):
        """Sets the announced of this NodePeersResponse.


        :param announced: The announced of this NodePeersResponse.  # noqa: E501
        :type: list[AnnouncedPeer]
        """
        if announced is None:
            raise ValueError("Invalid value for `announced`, must not be `None`")  # noqa: E501

        self._announced = announced

    @property
    def connected(self):
        """Gets the connected of this NodePeersResponse.  # noqa: E501


        :return: The connected of this NodePeersResponse.  # noqa: E501
        :rtype: list[PeerInfo]
        """
        return self._connected

    @connected.setter
    def connected(self, connected):
        """Sets the connected of this NodePeersResponse.


        :param connected: The connected of this NodePeersResponse.  # noqa: E501
        :type: list[PeerInfo]
        """
        if connected is None:
            raise ValueError("Invalid value for `connected`, must not be `None`")  # noqa: E501

        self._connected = connected

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NodePeersResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodePeersResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
