# coding: utf-8

"""
    hoprd-api

    This Rest API enables developers to interact with a hoprd node programatically through HTTP.  # noqa: E501

    OpenAPI spec version: 3.2.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OpenChannelBodyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'str',
        'peer_address': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'peer_address': 'peerAddress'
    }

    def __init__(self, amount=None, peer_address=None):  # noqa: E501
        """OpenChannelBodyRequest - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._peer_address = None
        self.discriminator = None
        self.amount = amount
        self.peer_address = peer_address

    @property
    def amount(self):
        """Gets the amount of this OpenChannelBodyRequest.  # noqa: E501

        Initial amount of stake in HOPR tokens.  # noqa: E501

        :return: The amount of this OpenChannelBodyRequest.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this OpenChannelBodyRequest.

        Initial amount of stake in HOPR tokens.  # noqa: E501

        :param amount: The amount of this OpenChannelBodyRequest.  # noqa: E501
        :type: str
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def peer_address(self):
        """Gets the peer_address of this OpenChannelBodyRequest.  # noqa: E501

        On-chain address of the counterparty.  # noqa: E501

        :return: The peer_address of this OpenChannelBodyRequest.  # noqa: E501
        :rtype: str
        """
        return self._peer_address

    @peer_address.setter
    def peer_address(self, peer_address):
        """Sets the peer_address of this OpenChannelBodyRequest.

        On-chain address of the counterparty.  # noqa: E501

        :param peer_address: The peer_address of this OpenChannelBodyRequest.  # noqa: E501
        :type: str
        """
        if peer_address is None:
            raise ValueError("Invalid value for `peer_address`, must not be `None`")  # noqa: E501

        self._peer_address = peer_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OpenChannelBodyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OpenChannelBodyRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
