# coding: utf-8

"""
    hoprd-api

    API server using the hopr-lib created HOPR node and exposing it using a HTTP REST API  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OpenChannelReceipt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel_id': 'str',
        'transaction_receipt': 'str'
    }

    attribute_map = {
        'channel_id': 'channelId',
        'transaction_receipt': 'transactionReceipt'
    }

    def __init__(self, channel_id=None, transaction_receipt=None):  # noqa: E501
        """OpenChannelReceipt - a model defined in Swagger"""  # noqa: E501
        self._channel_id = None
        self._transaction_receipt = None
        self.discriminator = None
        self.channel_id = channel_id
        self.transaction_receipt = transaction_receipt

    @property
    def channel_id(self):
        """Gets the channel_id of this OpenChannelReceipt.  # noqa: E501


        :return: The channel_id of this OpenChannelReceipt.  # noqa: E501
        :rtype: str
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """Sets the channel_id of this OpenChannelReceipt.


        :param channel_id: The channel_id of this OpenChannelReceipt.  # noqa: E501
        :type: str
        """
        if channel_id is None:
            raise ValueError("Invalid value for `channel_id`, must not be `None`")  # noqa: E501

        self._channel_id = channel_id

    @property
    def transaction_receipt(self):
        """Gets the transaction_receipt of this OpenChannelReceipt.  # noqa: E501


        :return: The transaction_receipt of this OpenChannelReceipt.  # noqa: E501
        :rtype: str
        """
        return self._transaction_receipt

    @transaction_receipt.setter
    def transaction_receipt(self, transaction_receipt):
        """Sets the transaction_receipt of this OpenChannelReceipt.


        :param transaction_receipt: The transaction_receipt of this OpenChannelReceipt.  # noqa: E501
        :type: str
        """
        if transaction_receipt is None:
            raise ValueError("Invalid value for `transaction_receipt`, must not be `None`")  # noqa: E501

        self._transaction_receipt = transaction_receipt

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OpenChannelReceipt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OpenChannelReceipt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
