# coding: utf-8

"""
    hoprd-api

    API server using the hopr-lib created HOPR node and exposing it using a HTTP REST API  # noqa: E501

    OpenAPI spec version: 0.2.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PeerInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'backoff': 'float',
        'heartbeats': 'HeartbeatInfo',
        'is_new': 'bool',
        'last_seen': 'int',
        'last_seen_latency': 'int',
        'multiaddr': 'str',
        'peer_address': 'str',
        'peer_id': 'str',
        'quality': 'float',
        'reported_version': 'str'
    }

    attribute_map = {
        'backoff': 'backoff',
        'heartbeats': 'heartbeats',
        'is_new': 'isNew',
        'last_seen': 'lastSeen',
        'last_seen_latency': 'lastSeenLatency',
        'multiaddr': 'multiaddr',
        'peer_address': 'peerAddress',
        'peer_id': 'peerId',
        'quality': 'quality',
        'reported_version': 'reportedVersion'
    }

    def __init__(self, backoff=None, heartbeats=None, is_new=None, last_seen=None, last_seen_latency=None, multiaddr=None, peer_address=None, peer_id=None, quality=None, reported_version=None):  # noqa: E501
        """PeerInfo - a model defined in Swagger"""  # noqa: E501
        self._backoff = None
        self._heartbeats = None
        self._is_new = None
        self._last_seen = None
        self._last_seen_latency = None
        self._multiaddr = None
        self._peer_address = None
        self._peer_id = None
        self._quality = None
        self._reported_version = None
        self.discriminator = None
        self.backoff = backoff
        self.heartbeats = heartbeats
        self.is_new = is_new
        self.last_seen = last_seen
        self.last_seen_latency = last_seen_latency
        if multiaddr is not None:
            self.multiaddr = multiaddr
        if peer_address is not None:
            self.peer_address = peer_address
        self.peer_id = peer_id
        self.quality = quality
        self.reported_version = reported_version

    @property
    def backoff(self):
        """Gets the backoff of this PeerInfo.  # noqa: E501


        :return: The backoff of this PeerInfo.  # noqa: E501
        :rtype: float
        """
        return self._backoff

    @backoff.setter
    def backoff(self, backoff):
        """Sets the backoff of this PeerInfo.


        :param backoff: The backoff of this PeerInfo.  # noqa: E501
        :type: float
        """
        if backoff is None:
            raise ValueError("Invalid value for `backoff`, must not be `None`")  # noqa: E501

        self._backoff = backoff

    @property
    def heartbeats(self):
        """Gets the heartbeats of this PeerInfo.  # noqa: E501


        :return: The heartbeats of this PeerInfo.  # noqa: E501
        :rtype: HeartbeatInfo
        """
        return self._heartbeats

    @heartbeats.setter
    def heartbeats(self, heartbeats):
        """Sets the heartbeats of this PeerInfo.


        :param heartbeats: The heartbeats of this PeerInfo.  # noqa: E501
        :type: HeartbeatInfo
        """
        if heartbeats is None:
            raise ValueError("Invalid value for `heartbeats`, must not be `None`")  # noqa: E501

        self._heartbeats = heartbeats

    @property
    def is_new(self):
        """Gets the is_new of this PeerInfo.  # noqa: E501


        :return: The is_new of this PeerInfo.  # noqa: E501
        :rtype: bool
        """
        return self._is_new

    @is_new.setter
    def is_new(self, is_new):
        """Sets the is_new of this PeerInfo.


        :param is_new: The is_new of this PeerInfo.  # noqa: E501
        :type: bool
        """
        if is_new is None:
            raise ValueError("Invalid value for `is_new`, must not be `None`")  # noqa: E501

        self._is_new = is_new

    @property
    def last_seen(self):
        """Gets the last_seen of this PeerInfo.  # noqa: E501


        :return: The last_seen of this PeerInfo.  # noqa: E501
        :rtype: int
        """
        return self._last_seen

    @last_seen.setter
    def last_seen(self, last_seen):
        """Sets the last_seen of this PeerInfo.


        :param last_seen: The last_seen of this PeerInfo.  # noqa: E501
        :type: int
        """
        if last_seen is None:
            raise ValueError("Invalid value for `last_seen`, must not be `None`")  # noqa: E501

        self._last_seen = last_seen

    @property
    def last_seen_latency(self):
        """Gets the last_seen_latency of this PeerInfo.  # noqa: E501


        :return: The last_seen_latency of this PeerInfo.  # noqa: E501
        :rtype: int
        """
        return self._last_seen_latency

    @last_seen_latency.setter
    def last_seen_latency(self, last_seen_latency):
        """Sets the last_seen_latency of this PeerInfo.


        :param last_seen_latency: The last_seen_latency of this PeerInfo.  # noqa: E501
        :type: int
        """
        if last_seen_latency is None:
            raise ValueError("Invalid value for `last_seen_latency`, must not be `None`")  # noqa: E501

        self._last_seen_latency = last_seen_latency

    @property
    def multiaddr(self):
        """Gets the multiaddr of this PeerInfo.  # noqa: E501


        :return: The multiaddr of this PeerInfo.  # noqa: E501
        :rtype: str
        """
        return self._multiaddr

    @multiaddr.setter
    def multiaddr(self, multiaddr):
        """Sets the multiaddr of this PeerInfo.


        :param multiaddr: The multiaddr of this PeerInfo.  # noqa: E501
        :type: str
        """

        self._multiaddr = multiaddr

    @property
    def peer_address(self):
        """Gets the peer_address of this PeerInfo.  # noqa: E501


        :return: The peer_address of this PeerInfo.  # noqa: E501
        :rtype: str
        """
        return self._peer_address

    @peer_address.setter
    def peer_address(self, peer_address):
        """Sets the peer_address of this PeerInfo.


        :param peer_address: The peer_address of this PeerInfo.  # noqa: E501
        :type: str
        """

        self._peer_address = peer_address

    @property
    def peer_id(self):
        """Gets the peer_id of this PeerInfo.  # noqa: E501


        :return: The peer_id of this PeerInfo.  # noqa: E501
        :rtype: str
        """
        return self._peer_id

    @peer_id.setter
    def peer_id(self, peer_id):
        """Sets the peer_id of this PeerInfo.


        :param peer_id: The peer_id of this PeerInfo.  # noqa: E501
        :type: str
        """
        if peer_id is None:
            raise ValueError("Invalid value for `peer_id`, must not be `None`")  # noqa: E501

        self._peer_id = peer_id

    @property
    def quality(self):
        """Gets the quality of this PeerInfo.  # noqa: E501


        :return: The quality of this PeerInfo.  # noqa: E501
        :rtype: float
        """
        return self._quality

    @quality.setter
    def quality(self, quality):
        """Sets the quality of this PeerInfo.


        :param quality: The quality of this PeerInfo.  # noqa: E501
        :type: float
        """
        if quality is None:
            raise ValueError("Invalid value for `quality`, must not be `None`")  # noqa: E501

        self._quality = quality

    @property
    def reported_version(self):
        """Gets the reported_version of this PeerInfo.  # noqa: E501


        :return: The reported_version of this PeerInfo.  # noqa: E501
        :rtype: str
        """
        return self._reported_version

    @reported_version.setter
    def reported_version(self, reported_version):
        """Sets the reported_version of this PeerInfo.


        :param reported_version: The reported_version of this PeerInfo.  # noqa: E501
        :type: str
        """
        if reported_version is None:
            raise ValueError("Invalid value for `reported_version`, must not be `None`")  # noqa: E501

        self._reported_version = reported_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PeerInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PeerInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
