# coding: utf-8

"""
    HOPRd Rest API v3

    This Rest API enables developers to interact with a hoprd node programatically.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: tech@hoprnet.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Ticket(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel_id': 'ChannelId',
        'amount': 'str',
        'index': 'str',
        'index_offset': 'str',
        'channel_epoch': 'str',
        'win_prob': 'str',
        'signature': 'Signature'
    }

    attribute_map = {
        'channel_id': 'channelId',
        'amount': 'amount',
        'index': 'index',
        'index_offset': 'indexOffset',
        'channel_epoch': 'channelEpoch',
        'win_prob': 'winProb',
        'signature': 'signature'
    }

    def __init__(self, channel_id=None, amount=None, index=None, index_offset=None, channel_epoch=None, win_prob=None, signature=None):  # noqa: E501
        """Ticket - a model defined in Swagger"""  # noqa: E501
        self._channel_id = None
        self._amount = None
        self._index = None
        self._index_offset = None
        self._channel_epoch = None
        self._win_prob = None
        self._signature = None
        self.discriminator = None
        if channel_id is not None:
            self.channel_id = channel_id
        if amount is not None:
            self.amount = amount
        if index is not None:
            self.index = index
        if index_offset is not None:
            self.index_offset = index_offset
        if channel_epoch is not None:
            self.channel_epoch = channel_epoch
        if win_prob is not None:
            self.win_prob = win_prob
        if signature is not None:
            self.signature = signature

    @property
    def channel_id(self):
        """Gets the channel_id of this Ticket.  # noqa: E501


        :return: The channel_id of this Ticket.  # noqa: E501
        :rtype: ChannelId
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """Sets the channel_id of this Ticket.


        :param channel_id: The channel_id of this Ticket.  # noqa: E501
        :type: ChannelId
        """

        self._channel_id = channel_id

    @property
    def amount(self):
        """Gets the amount of this Ticket.  # noqa: E501

        The ticket's value in HOPR. Only relevant if ticket is a win.  # noqa: E501

        :return: The amount of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Ticket.

        The ticket's value in HOPR. Only relevant if ticket is a win.  # noqa: E501

        :param amount: The amount of this Ticket.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def index(self):
        """Gets the index of this Ticket.  # noqa: E501

        Each ticket is labeled by an ongoing serial number named ticket index i and its current value is stored in the smart contract.  # noqa: E501

        :return: The index of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this Ticket.

        Each ticket is labeled by an ongoing serial number named ticket index i and its current value is stored in the smart contract.  # noqa: E501

        :param index: The index of this Ticket.  # noqa: E501
        :type: str
        """

        self._index = index

    @property
    def index_offset(self):
        """Gets the index_offset of this Ticket.  # noqa: E501

        Offset by which the on-chain stored ticket index gets increased when redeeming the ticket. Used to aggregate tickets.  # noqa: E501

        :return: The index_offset of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._index_offset

    @index_offset.setter
    def index_offset(self, index_offset):
        """Sets the index_offset of this Ticket.

        Offset by which the on-chain stored ticket index gets increased when redeeming the ticket. Used to aggregate tickets.  # noqa: E501

        :param index_offset: The index_offset of this Ticket.  # noqa: E501
        :type: str
        """

        self._index_offset = index_offset

    @property
    def channel_epoch(self):
        """Gets the channel_epoch of this Ticket.  # noqa: E501

        Payment channels might run through multiple open and close sequences, this epoch tracks the sequence.  # noqa: E501

        :return: The channel_epoch of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._channel_epoch

    @channel_epoch.setter
    def channel_epoch(self, channel_epoch):
        """Sets the channel_epoch of this Ticket.

        Payment channels might run through multiple open and close sequences, this epoch tracks the sequence.  # noqa: E501

        :param channel_epoch: The channel_epoch of this Ticket.  # noqa: E501
        :type: str
        """

        self._channel_epoch = channel_epoch

    @property
    def win_prob(self):
        """Gets the win_prob of this Ticket.  # noqa: E501

        The ticket's winning probability, going from 0.0 to 1.0 where 0.0 ~= 0% winning probability and 1.0 equals 100% winning probability.  # noqa: E501

        :return: The win_prob of this Ticket.  # noqa: E501
        :rtype: str
        """
        return self._win_prob

    @win_prob.setter
    def win_prob(self, win_prob):
        """Sets the win_prob of this Ticket.

        The ticket's winning probability, going from 0.0 to 1.0 where 0.0 ~= 0% winning probability and 1.0 equals 100% winning probability.  # noqa: E501

        :param win_prob: The win_prob of this Ticket.  # noqa: E501
        :type: str
        """

        self._win_prob = win_prob

    @property
    def signature(self):
        """Gets the signature of this Ticket.  # noqa: E501


        :return: The signature of this Ticket.  # noqa: E501
        :rtype: Signature
        """
        return self._signature

    @signature.setter
    def signature(self, signature):
        """Sets the signature of this Ticket.


        :param signature: The signature of this Ticket.  # noqa: E501
        :type: Signature
        """

        self._signature = signature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Ticket, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Ticket):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
